// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType]
}
/** Content for Blog documents */
interface BlogDocumentData {
  /**
   * Título field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField
  /**
   * Texto field in *Blog*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField
  /**
   * Imagem de destaque field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<never>
  /**
   * Slice Zone field in *Blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice>
  /**
   * Meta Title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField
  /**
   * Meta Description field in *Blog*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  meta_description: prismic.RichTextField
  /**
   * Meta Image field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>
}
/**
 * Slice for *Blog → Slice Zone*
 *
 */
type BlogDocumentDataSlicesSlice = VejaTambemSlice
/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BlogDocumentData>, 'blog', Lang>
/** Content for Rodapé documents */
interface FooterDocumentData {
  /**
   * Título do Mapa field in *Rodapé*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Como chegar
   * - **API ID Path**: footer.title_map
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title_map: prismic.KeyTextField
  /**
   * Subtítulo do Mapa field in *Rodapé*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Nas nossas unidades Asa Sul e Asa Norte
   * - **API ID Path**: footer.subtitle_map
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  subtitle_map: prismic.KeyTextField
  /**
   * Título do Formulário field in *Rodapé*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: diga olá
   * - **API ID Path**: footer.title_form
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title_form: prismic.KeyTextField
  /**
   * Subtítulo do formulário field in *Rodapé*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Nos deixe saber em que podemos ajudar.
   * - **API ID Path**: footer.subtitle_form
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  subtitle_form: prismic.KeyTextField
  /**
   * Título unidade 1 field in *Rodapé*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Unidade Asa Sul
   * - **API ID Path**: footer.title_unity1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title_unity1: prismic.KeyTextField
  /**
   * Informações unicade 1 field in *Rodapé*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: ex: EQS 212/412...
   * - **API ID Path**: footer.info_unity1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  info_unity1: prismic.RichTextField
  /**
   * Localização unidade 1 field in *Rodapé*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.localization_unity1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/geopoint
   *
   */
  localization_unity1: prismic.GeoPointField
  /**
   * Título unidade 2 field in *Rodapé*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Unidade Asa Norte
   * - **API ID Path**: footer.title_unity2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title_unity2: prismic.KeyTextField
  /**
   * Informações unicade 2 field in *Rodapé*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.info_unity2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  info_unity2: prismic.RichTextField
  /**
   * Localização unidade 2 field in *Rodapé*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.localization_unity2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/geopoint
   *
   */
  localization_unity2: prismic.GeoPointField
  /**
   * Copyright field in *Rodapé*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: ©Copyright: Todos dos direitos reservados a Escola Canarinho
   * - **API ID Path**: footer.copyright
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  copyright: prismic.KeyTextField
}
/**
 * Rodapé document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    'footer',
    Lang
  >
/** Content for Home documents */
interface HomeDocumentData {
  /**
   * Título field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Escola Canarinho
   * - **API ID Path**: home.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>
  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField
  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  meta_description: prismic.RichTextField
  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>
}
/**
 * Slice for *Home → Slice Zone*
 *
 */
type HomeDocumentDataSlicesSlice =
  | BannerHomeSlice
  | ModalidadesSlice
  | NossaEscolaSlice
  | TourVirtualSlice
  | VideoYoutubeSlice
  | DepoimentosSlice
  | FotosInstagramSlice
/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, 'home', Lang>
/** Content for Menu lateral documents */
interface NavSideDocumentData {
  /**
   * Título do menu field in *Menu lateral*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Dia a dia
   * - **API ID Path**: nav_side.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField
  /**
   * Slice Zone field in *Menu lateral*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_side.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<NavSideDocumentDataSlicesSlice>
}
/**
 * Slice for *Menu lateral → Slice Zone*
 *
 */
type NavSideDocumentDataSlicesSlice = MenuSlice
/**
 * Menu lateral document from Prismic
 *
 * - **API ID**: `nav_side`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavSideDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavSideDocumentData>,
    'nav_side',
    Lang
  >
/** Content for Menu Social documents */
interface NavSocialDocumentData {
  /**
   * Slice Zone field in *Menu Social*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_social.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<NavSocialDocumentDataSlicesSlice>
}
/**
 * Slice for *Menu Social → Slice Zone*
 *
 */
type NavSocialDocumentDataSlicesSlice = SocialSlice
/**
 * Menu Social document from Prismic
 *
 * - **API ID**: `nav_social`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavSocialDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavSocialDocumentData>,
    'nav_social',
    Lang
  >
/** Content for Menu Superior documents */
interface NavTopDocumentData {
  /**
   * Mostrar botão de idioma? field in *Menu Superior*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: nav_top.button_language
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
   *
   */
  button_language: prismic.BooleanField
  /**
   * Texto Pré-Matricula field in *Menu Superior*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_top.text_registration
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  text_registration: prismic.KeyTextField
  /**
   * Link Pré-Matricula field in *Menu Superior*
   *
   * - **Field Type**: Link
   * - **Placeholder**: ex: /pre-registro
   * - **API ID Path**: nav_top.link_pre_registration
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link_pre_registration: prismic.LinkField
  /**
   * Text Espaço do Responsável field in *Menu Superior*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_top.text_responsible_space
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  text_responsible_space: prismic.KeyTextField
  /**
   * Link Espaço do Responsável field in *Menu Superior*
   *
   * - **Field Type**: Link
   * - **Placeholder**: ex: https://portal.sophia.com.br/SophiA_65/Acesso.aspx?escola=6296
   * - **API ID Path**: nav_top.link_responsible_space
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link_responsible_space: prismic.LinkField
  /**
   * Slice Zone field in *Menu Superior*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_top.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<NavTopDocumentDataSlicesSlice>
}
/**
 * Slice for *Menu Superior → Slice Zone*
 *
 */
type NavTopDocumentDataSlicesSlice = MenuSubmenuSlice
/**
 * Menu Superior document from Prismic
 *
 * - **API ID**: `nav_top`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavTopDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavTopDocumentData>,
    'nav_top',
    Lang
  >
/** Content for Página documents */
interface PageDocumentData {
  /**
   * Título field in *Página*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Nossa Escola
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField
  /**
   * Texto field in *Página*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.texto
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  texto: prismic.RichTextField
  /**
   * Imagem de destaque field in *Página*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<never>
  /**
   * Slice Zone field in *Página*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>
  /**
   * Meta Title field in *Página*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField
  /**
   * Meta Description field in *Página*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  meta_description: prismic.RichTextField
  /**
   * Meta Image field in *Página*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>
}
/**
 * Slice for *Página → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice =
  | DocumentosSlice
  | VejaTambemSlice
  | GaleriaFotosSlice
  | TourVirtualSlice
  | VideoYoutubeSlice
/**
 * Página document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, 'page', Lang>
export type AllDocumentTypes =
  | BlogDocument
  | FooterDocument
  | HomeDocument
  | NavSideDocument
  | NavSocialDocument
  | NavTopDocument
  | PageDocument
/**
 * Primary content in BannerHome → Primary
 *
 */
interface BannerHomeSliceDefaultPrimary {
  /**
   * Título field in *BannerHome → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_home.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField
}
/**
 * Default variation for BannerHome Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BannerHomeSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<BannerHomeSliceDefaultPrimary>,
  never
>
/**
 * Slice variation for *BannerHome*
 *
 */
type BannerHomeSliceVariation = BannerHomeSliceDefault
/**
 * BannerHome Shared Slice
 *
 * - **API ID**: `banner_home`
 * - **Description**: `BannerHome`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BannerHomeSlice = prismic.SharedSlice<
  'banner_home',
  BannerHomeSliceVariation
>
/**
 * Primary content in Depoimentos → Primary
 *
 */
interface DepoimentosSliceDefaultPrimary {
  /**
   * Título field in *Depoimentos → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Por que Canarinho?
   * - **API ID Path**: depoimentos.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField
  /**
   * Subtítulo field in *Depoimentos → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Depoimentos de quem passou por aqui
   * - **API ID Path**: depoimentos.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  subtitle: prismic.KeyTextField
}
/**
 * Item in Depoimentos → Items
 *
 */
export interface DepoimentosSliceDefaultItem {
  /**
   * Nome field in *Depoimentos → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Lucas
   * - **API ID Path**: depoimentos.items[].name
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismic.KeyTextField
  /**
   * Depoimento field in *Depoimentos → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: ex: Melhor escola do mundo...
   * - **API ID Path**: depoimentos.items[].testimony
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  testimony: prismic.RichTextField
}
/**
 * Default variation for Depoimentos Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type DepoimentosSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<DepoimentosSliceDefaultPrimary>,
  Simplify<DepoimentosSliceDefaultItem>
>
/**
 * Slice variation for *Depoimentos*
 *
 */
type DepoimentosSliceVariation = DepoimentosSliceDefault
/**
 * Depoimentos Shared Slice
 *
 * - **API ID**: `depoimentos`
 * - **Description**: `Depoimentos`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type DepoimentosSlice = prismic.SharedSlice<
  'depoimentos',
  DepoimentosSliceVariation
>
/**
 * Item in Documentos → Items
 *
 */
export interface DocumentosSliceDefaultItem {
  /**
   * Nome do documento field in *Documentos → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: documentos.items[].name
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismic.KeyTextField
  /**
   * Documento field in *Documentos → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: documentos.items[].document
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  document: prismic.LinkToMediaField
}
/**
 * Default variation for Documentos Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type DocumentosSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  Simplify<DocumentosSliceDefaultItem>
>
/**
 * Slice variation for *Documentos*
 *
 */
type DocumentosSliceVariation = DocumentosSliceDefault
/**
 * Documentos Shared Slice
 *
 * - **API ID**: `documentos`
 * - **Description**: `Documentos`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type DocumentosSlice = prismic.SharedSlice<
  'documentos',
  DocumentosSliceVariation
>
/**
 * Primary content in FotosInstagram → Primary
 *
 */
interface FotosInstagramSliceDefaultPrimary {
  /**
   * Título field in *FotosInstagram → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Fotos
   * - **API ID Path**: fotos_instagram.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField
  /**
   * Subtítulo field in *FotosInstagram → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Acompanhe a gente pelo instagram
   * - **API ID Path**: fotos_instagram.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  subtitle: prismic.KeyTextField
  /**
   * Texto do botão field in *FotosInstagram → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Instagram
   * - **API ID Path**: fotos_instagram.primary.button_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  button_text: prismic.KeyTextField
  /**
   * Link do botão field in *FotosInstagram → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: ex: http://...
   * - **API ID Path**: fotos_instagram.primary.button_link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  button_link: prismic.LinkField
}
/**
 * Item in FotosInstagram → Items
 *
 */
export interface FotosInstagramSliceDefaultItem {
  /**
   * Fotos field in *FotosInstagram → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: fotos_instagram.items[].photo
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  photo: prismic.ImageField<never>
}
/**
 * Default variation for FotosInstagram Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FotosInstagramSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FotosInstagramSliceDefaultPrimary>,
  Simplify<FotosInstagramSliceDefaultItem>
>
/**
 * Slice variation for *FotosInstagram*
 *
 */
type FotosInstagramSliceVariation = FotosInstagramSliceDefault
/**
 * FotosInstagram Shared Slice
 *
 * - **API ID**: `fotos_instagram`
 * - **Description**: `FotosInstagram`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FotosInstagramSlice = prismic.SharedSlice<
  'fotos_instagram',
  FotosInstagramSliceVariation
>
/**
 * Primary content in GaleriaFotos → Primary
 *
 */
interface GaleriaFotosSliceDefaultPrimary {
  /**
   * Título field in *GaleriaFotos → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: galeria_fotos.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField
  /**
   * Texto field in *GaleriaFotos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: galeria_fotos.primary.text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField
  /**
   * Texto do botão field in *GaleriaFotos → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: galeria_fotos.primary.button_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  button_text: prismic.KeyTextField
}
/**
 * Item in GaleriaFotos → Items
 *
 */
export interface GaleriaFotosSliceDefaultItem {
  /**
   * Foto field in *GaleriaFotos → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: galeria_fotos.items[].photo
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  photo: prismic.ImageField<never>
}
/**
 * Default variation for GaleriaFotos Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type GaleriaFotosSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<GaleriaFotosSliceDefaultPrimary>,
  Simplify<GaleriaFotosSliceDefaultItem>
>
/**
 * Slice variation for *GaleriaFotos*
 *
 */
type GaleriaFotosSliceVariation = GaleriaFotosSliceDefault
/**
 * GaleriaFotos Shared Slice
 *
 * - **API ID**: `galeria_fotos`
 * - **Description**: `GaleriaFotos`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type GaleriaFotosSlice = prismic.SharedSlice<
  'galeria_fotos',
  GaleriaFotosSliceVariation
>
/**
 * Item in Menu → Items
 *
 */
export interface MenuSliceDefaultItem {
  /**
   * Nome do Item field in *Menu → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Nossa Escola
   * - **API ID Path**: menu.items[].name
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismic.KeyTextField
  /**
   * Link do item field in *Menu → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: ex: /nossa-escola
   * - **API ID Path**: menu.items[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField
}
/**
 * Default variation for Menu Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MenuSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  Simplify<MenuSliceDefaultItem>
>
/**
 * Slice variation for *Menu*
 *
 */
type MenuSliceVariation = MenuSliceDefault
/**
 * Menu Shared Slice
 *
 * - **API ID**: `menu`
 * - **Description**: `Menu`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MenuSlice = prismic.SharedSlice<'menu', MenuSliceVariation>
/**
 * Primary content in MenuItem → Primary
 *
 */
interface MenuSubmenuSliceDefaultPrimary {
  /**
   * Nome do item field in *MenuItem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_submenu.primary.name
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismic.KeyTextField
  /**
   * Link do item field in *MenuItem → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_submenu.primary.link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField
}
/**
 * Item in MenuItem → Items
 *
 */
export interface MenuSubmenuSliceDefaultItem {
  /**
   * Nome do subitem field in *MenuItem → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_submenu.items[].name
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismic.KeyTextField
  /**
   * Link do subitem field in *MenuItem → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_submenu.items[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField
}
/**
 * Default variation for MenuItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MenuSubmenuSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<MenuSubmenuSliceDefaultPrimary>,
  Simplify<MenuSubmenuSliceDefaultItem>
>
/**
 * Slice variation for *MenuItem*
 *
 */
type MenuSubmenuSliceVariation = MenuSubmenuSliceDefault
/**
 * MenuItem Shared Slice
 *
 * - **API ID**: `menu_submenu`
 * - **Description**: `MenuSubmenu`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MenuSubmenuSlice = prismic.SharedSlice<
  'menu_submenu',
  MenuSubmenuSliceVariation
>
/**
 * Item in Modalidades → Items
 *
 */
export interface ModalidadesSliceDefaultItem {
  /**
   * Cor field in *Modalidades → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Escolha uma cor
   * - **Default Value**: Amarelo
   * - **API ID Path**: modalidades.items[].color
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  color: prismic.SelectField<'Amarelo' | 'Azul' | 'Laranja', 'filled'>
  /**
   * Icone field in *Modalidades → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: modalidades.items[].icon
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  icon: prismic.ImageField<never>
  /**
   * Título field in *Modalidades → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Berçario
   * - **API ID Path**: modalidades.items[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField
  /**
   * Subtítulo field in *Modalidades → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: de 0 a 3 anos
   * - **API ID Path**: modalidades.items[].subtitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  subtitle: prismic.KeyTextField
  /**
   * Texto field in *Modalidades → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: ex: Um ambiente com muito...
   * - **API ID Path**: modalidades.items[].text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField
  /**
   * Link field in *Modalidades → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: ex: /bercario
   * - **API ID Path**: modalidades.items[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField
}
/**
 * Default variation for Modalidades Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ModalidadesSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  Simplify<ModalidadesSliceDefaultItem>
>
/**
 * Slice variation for *Modalidades*
 *
 */
type ModalidadesSliceVariation = ModalidadesSliceDefault
/**
 * Modalidades Shared Slice
 *
 * - **API ID**: `modalidades`
 * - **Description**: `Modalidades`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ModalidadesSlice = prismic.SharedSlice<
  'modalidades',
  ModalidadesSliceVariation
>
/**
 * Primary content in NossaEscola → Primary
 *
 */
interface NossaEscolaSliceDefaultPrimary {
  /**
   * Título field in *NossaEscola → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nossa_escola.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField
  /**
   * Subtítulo field in *NossaEscola → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nossa_escola.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  subtitle: prismic.KeyTextField
  /**
   * Texto field in *NossaEscola → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nossa_escola.primary.text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField
  /**
   * Texto do botão field in *NossaEscola → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nossa_escola.primary.button_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  button_text: prismic.KeyTextField
  /**
   * Link do botão field in *NossaEscola → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: nossa_escola.primary.button_link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  button_link: prismic.LinkField
  /**
   * Thumb do vídeo field in *NossaEscola → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nossa_escola.primary.thumb
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  thumb: prismic.ImageField<never>
  /**
   * Link do vídeo (Youtube) field in *NossaEscola → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: nossa_escola.primary.video
   * - **Documentation**: https://prismic.io/docs/core-concepts/embed
   *
   */
  video: prismic.EmbedField
}
/**
 * Default variation for NossaEscola Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NossaEscolaSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<NossaEscolaSliceDefaultPrimary>,
  never
>
/**
 * Slice variation for *NossaEscola*
 *
 */
type NossaEscolaSliceVariation = NossaEscolaSliceDefault
/**
 * NossaEscola Shared Slice
 *
 * - **API ID**: `nossa_escola`
 * - **Description**: `NossaEscola`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NossaEscolaSlice = prismic.SharedSlice<
  'nossa_escola',
  NossaEscolaSliceVariation
>
/**
 * Item in Social → Items
 *
 */
export interface SocialSliceDefaultItem {
  /**
   * Nome da Rede field in *Social → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Instagram
   * - **API ID Path**: social.items[].name
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismic.KeyTextField
  /**
   * Link da Rede field in *Social → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: ex: http://Instagram.com
   * - **API ID Path**: social.items[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.LinkField
  /**
   * Icone da Rede field in *Social → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: social.items[].icon
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  icon: prismic.ImageField<never>
}
/**
 * Default variation for Social Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SocialSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  Simplify<SocialSliceDefaultItem>
>
/**
 * Slice variation for *Social*
 *
 */
type SocialSliceVariation = SocialSliceDefault
/**
 * Social Shared Slice
 *
 * - **API ID**: `social`
 * - **Description**: `Social`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SocialSlice = prismic.SharedSlice<'social', SocialSliceVariation>
/**
 * Primary content in TourVirtual → Primary
 *
 */
interface TourVirtualSliceDefaultPrimary {
  /**
   * Título field in *TourVirtual → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Tour Virtual
   * - **API ID Path**: tour_virtual.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField
  /**
   * Subtítulo field in *TourVirtual → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Conheça as unidades
   * - **API ID Path**: tour_virtual.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  subtitle: prismic.KeyTextField
  /**
   * Texto do botão 1 field in *TourVirtual → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Asa sul
   * - **API ID Path**: tour_virtual.primary.button1_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  button1_text: prismic.KeyTextField
  /**
   * Link do botão 1 field in *TourVirtual → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: ex: http://...
   * - **API ID Path**: tour_virtual.primary.button1_link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  button1_link: prismic.LinkField
  /**
   * Texto do botão 2 field in *TourVirtual → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Asa norte
   * - **API ID Path**: tour_virtual.primary.button2_text
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  button2_text: prismic.KeyTextField
  /**
   * Link do botão 2 field in *TourVirtual → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: ex: http://...
   * - **API ID Path**: tour_virtual.primary.button2_link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  button2_link: prismic.LinkField
}
/**
 * Default variation for TourVirtual Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TourVirtualSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TourVirtualSliceDefaultPrimary>,
  never
>
/**
 * Slice variation for *TourVirtual*
 *
 */
type TourVirtualSliceVariation = TourVirtualSliceDefault
/**
 * TourVirtual Shared Slice
 *
 * - **API ID**: `tour_virtual`
 * - **Description**: `TourVirtual`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TourVirtualSlice = prismic.SharedSlice<
  'tour_virtual',
  TourVirtualSliceVariation
>
/**
 * Default variation for TrabalheConosco Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TrabalheConoscoSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  never
>
/**
 * Slice variation for *TrabalheConosco*
 *
 */
type TrabalheConoscoSliceVariation = TrabalheConoscoSliceDefault
/**
 * TrabalheConosco Shared Slice
 *
 * - **API ID**: `trabalhe_conosco`
 * - **Description**: `TrabalheConosco`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TrabalheConoscoSlice = prismic.SharedSlice<
  'trabalhe_conosco',
  TrabalheConoscoSliceVariation
>
/**
 * Primary content in VejaTambem → Primary
 *
 */
interface VejaTambemSliceDefaultPrimary {
  /**
   * Título field in *VejaTambem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: Veja também
   * - **API ID Path**: veja_tambem.primary.title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField
}
/**
 * Item in VejaTambem → Items
 *
 */
export interface VejaTambemSliceDefaultItem {
  /**
   * Nome do link field in *VejaTambem → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: veja_tambem.items[].name
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismic.KeyTextField
  /**
   * Link field in *VejaTambem → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: veja_tambem.items[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismic.RelationField<'page'>
}
/**
 * Default variation for VejaTambem Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type VejaTambemSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<VejaTambemSliceDefaultPrimary>,
  Simplify<VejaTambemSliceDefaultItem>
>
/**
 * Slice variation for *VejaTambem*
 *
 */
type VejaTambemSliceVariation = VejaTambemSliceDefault
/**
 * VejaTambem Shared Slice
 *
 * - **API ID**: `veja_tambem`
 * - **Description**: `VejaTambem`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type VejaTambemSlice = prismic.SharedSlice<
  'veja_tambem',
  VejaTambemSliceVariation
>
/**
 * Primary content in VideoYoutube → Primary
 *
 */
interface VideoYoutubeSliceDefaultPrimary {
  /**
   * Link vídeo do youtube field in *VideoYoutube → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: video_youtube.primary.video
   * - **Documentation**: https://prismic.io/docs/core-concepts/embed
   *
   */
  video: prismic.EmbedField
}
/**
 * Default variation for VideoYoutube Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type VideoYoutubeSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<VideoYoutubeSliceDefaultPrimary>,
  never
>
/**
 * Slice variation for *VideoYoutube*
 *
 */
type VideoYoutubeSliceVariation = VideoYoutubeSliceDefault
/**
 * VideoYoutube Shared Slice
 *
 * - **API ID**: `video_youtube`
 * - **Description**: `VideoYoutube`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type VideoYoutubeSlice = prismic.SharedSlice<
  'video_youtube',
  VideoYoutubeSliceVariation
>
declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>
  }
  namespace Content {
    export type {
      BlogDocumentData,
      BlogDocumentDataSlicesSlice,
      BlogDocument,
      FooterDocumentData,
      FooterDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      HomeDocument,
      NavSideDocumentData,
      NavSideDocumentDataSlicesSlice,
      NavSideDocument,
      NavSocialDocumentData,
      NavSocialDocumentDataSlicesSlice,
      NavSocialDocument,
      NavTopDocumentData,
      NavTopDocumentDataSlicesSlice,
      NavTopDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PageDocument,
      AllDocumentTypes,
      BannerHomeSliceDefaultPrimary,
      BannerHomeSliceDefault,
      BannerHomeSliceVariation,
      BannerHomeSlice,
      DepoimentosSliceDefaultPrimary,
      DepoimentosSliceDefaultItem,
      DepoimentosSliceDefault,
      DepoimentosSliceVariation,
      DepoimentosSlice,
      DocumentosSliceDefaultItem,
      DocumentosSliceDefault,
      DocumentosSliceVariation,
      DocumentosSlice,
      FotosInstagramSliceDefaultPrimary,
      FotosInstagramSliceDefaultItem,
      FotosInstagramSliceDefault,
      FotosInstagramSliceVariation,
      FotosInstagramSlice,
      GaleriaFotosSliceDefaultPrimary,
      GaleriaFotosSliceDefaultItem,
      GaleriaFotosSliceDefault,
      GaleriaFotosSliceVariation,
      GaleriaFotosSlice,
      MenuSliceDefaultItem,
      MenuSliceDefault,
      MenuSliceVariation,
      MenuSlice,
      MenuSubmenuSliceDefaultPrimary,
      MenuSubmenuSliceDefaultItem,
      MenuSubmenuSliceDefault,
      MenuSubmenuSliceVariation,
      MenuSubmenuSlice,
      ModalidadesSliceDefaultItem,
      ModalidadesSliceDefault,
      ModalidadesSliceVariation,
      ModalidadesSlice,
      NossaEscolaSliceDefaultPrimary,
      NossaEscolaSliceDefault,
      NossaEscolaSliceVariation,
      NossaEscolaSlice,
      SocialSliceDefaultItem,
      SocialSliceDefault,
      SocialSliceVariation,
      SocialSlice,
      TourVirtualSliceDefaultPrimary,
      TourVirtualSliceDefault,
      TourVirtualSliceVariation,
      TourVirtualSlice,
      TrabalheConoscoSliceDefault,
      TrabalheConoscoSliceVariation,
      TrabalheConoscoSlice,
      VejaTambemSliceDefaultPrimary,
      VejaTambemSliceDefaultItem,
      VejaTambemSliceDefault,
      VejaTambemSliceVariation,
      VejaTambemSlice,
      VideoYoutubeSliceDefaultPrimary,
      VideoYoutubeSliceDefault,
      VideoYoutubeSliceVariation,
      VideoYoutubeSlice
    }
  }
}
