// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  banner_home: dynamic(() => import('./BannerHome')),
  depoimentos: dynamic(() => import('./Depoimentos')),
  documentos: dynamic(() => import('./Documentos')),
  fotos_instagram: dynamic(() => import('./FotosInstagram')),
  galeria_fotos: dynamic(() => import('./GaleriaFotos')),
  menu: dynamic(() => import('./Menu')),
  menu_submenu: dynamic(() => import('./MenuItem')),
  modalidades: dynamic(() => import('./Modalidades')),
  nossa_escola: dynamic(() => import('./NossaEscola')),
  social: dynamic(() => import('./Social')),
  tour_virtual: dynamic(() => import('./TourVirtual')),
  veja_tambem: dynamic(() => import('./VejaTambem')),
  video_youtube: dynamic(() => import('./VideoYoutube'))
}
