import { useLocale } from 'next-intl'
import { notFound } from 'next/navigation'
import { Sofia, Comic_Neue, Mulish } from 'next/font/google'

import './globals.css'

// const inter = Inter({ subsets: ['latin'] })
const sofia = Sofia({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-sofia'
})
const comic_neue = Comic_Neue({
  weight: ['700'],
  subsets: ['latin'],
  variable: '--font-comic-neue'
})
const mulish = Mulish({ subsets: ['latin'], variable: '--font-mulish' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

interface LayoutProps {
  children: React.ReactNode
  params: {
    locale: string
  }
}

export default function RootLayout({ children, params }: LayoutProps) {
  const locale = useLocale()

  // Show a 404 error if the user requests an unknown locale
  if (params.locale !== locale) {
    notFound()
  }

  return (
    <html lang={locale}>
      <body
        className={`${sofia.variable} ${comic_neue.variable} ${mulish.variable}`}
      >
        {children}
      </body>
    </html>
  )
}
